name: Check Code Quality

on: [push]

jobs:
  check-code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v7

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Check Code Quality
      run: |
        chmod +x .github/scripts/check_code_quality.sh
        ./.github/scripts/check_code_quality.sh
